Adaptation action: Section 1, 2, 3, 4, 5, 6
Sinamecc/sinamecc-backend pull request #63
Opened 2021-10-26 15:00 UTC by kixocaos

# This PR includes 
At the moment includes :
- section 1,2
- Added endpoint to change state (Add comments is missing)(FSM State #58 ):
    - **`PATCH`** `base-url/api/v1/adaptation-action/< adaptation-action-id>/`
    - **`BODY`**:
        ```
        {
            "fsm_state": "<state>"   
        }
        ```
    - return `MA info`

- Endpoint to Get All:
    - URL: `<base_url>/api/v1/adaptation-action/`
    - Type: `GET`
    <details>
    <summary>Return</summary>
        
        [
            {
                "id": "db1d6396-798e-40da-8b8a-52a1738a7eed",
                "fsm_state": {
                "state": "new",
                "label": "new label"
                },
                "report_organization": {
                "id": 1,
                "responsible_entity": "Test entity",
                "legal_identification": "402320808",
                "elaboration_date": null,
                "entity_address": "Test entity address",
                "report_organization_type": {
                    "id": 2,
                    "code": "2",
                    "entity_type": "Entidad privada",
                    "created": "2022-01-24T19:20:56.538422Z",
                    "updated": "2022-01-24T19:20:56.538439Z"
                },
                "contact": null,
                "created": "2022-01-24T19:21:21.220999Z",
                "updated": "2022-01-24T19:21:21.221020Z"
                },
                "address": {
                "id": 1,
                "description": "description address",
                "GIS": "x:222,y:333",
                "district": {
                    "id": 122,
                    "code": "02",
                    "name": "San José",
                    "canton": {
                    "id": 21,
                    "code": "01",
                    "name": "Alajuela",
                    "province": {
                        "id": 2,
                        "code": "2",
                        "name": "Alajuela",
                        "created": "2022-01-24T19:20:56.193954Z",
                        "updated": "2022-01-24T19:20:56.193966Z"
                    },
                    "created": "2022-01-24T19:20:56.194372Z",
                    "updated": "2022-01-24T19:20:56.194384Z"
                    },
                    "created": "2022-01-24T19:20:56.195157Z",
                    "updated": "2022-01-24T19:20:56.195169Z"
                },
                "created": "2022-01-24T19:21:21.228161Z",
                "updated": "2022-01-24T19:21:21.228179Z"
                },
                "adaptation_action_information": {
                "id": 1,
                "name": "Adaptation action information, test",
                "objective": "Objetive test",
                "description": "Description test",
                "meta": "Meta test",
                "adaptation_action_type": {
                    "id": 2,
                    "name": "Tipo B - Proyecto y programas",
                    "created": "2022-01-24T19:20:56.777779Z",
                    "updated": "2022-01-24T19:20:56.777810Z"
                },
                "ods": [
                    {
                    "id": 2,
                    "code": "2",
                    "name": "Hambre cero.",
                    "created": "2022-01-24T19:20:56.852971Z",
                    "updated": "2022-01-24T19:20:56.852992Z"
                    },
                    {
                    "id": 4,
                    "code": "4",
                    "name": "Educación de calidad.",
                    "created": "2022-01-24T19:20:56.854117Z",
                    "updated": "2022-01-24T19:20:56.854132Z"
                    }
                ],
                "created": "2022-01-24T19:21:21.234764Z",
                "updated": "2022-01-24T19:21:21.234783Z"
                },
                "activity": {
                "id": 180,
                "code": "02",
                "description": "Esta es una actividad test",
                "sub_topic": {
                    "id": 2,
                    "code": "2",
                    "name": "Transporte de carga",
                    "topic": {
                    "id": 1,
                    "code": "1",
                    "name": "Transporte",
                    "created": "2022-01-24T19:20:57.449792Z",
                    "updated": "2022-01-24T19:20:57.449804Z"
                    },
                    "created": "2022-01-24T19:20:57.455773Z",
                    "updated": "2022-01-24T19:20:57.455787Z"
                },
                "ndc_contribution": [
                    {
                    "id": 2,
                    "code": "2",
                    "description": "3.2. Costa Rica se compromete a desarrollar, durante el período de implementación de esta contribución, una planificación integrada intersectorial del proceso de electrificación de la demanda energética, que incorporará las necesidades de los diversos sectores y la diversidad de fuentes renovables de energía disponibles en las diferentes regiones del país.",
                    "other": null,
                    "ndc_area": {
                        "id": 2,
                        "code": "3",
                        "description": "3. Energía",
                        "other": null,
                        "created": "2022-01-24T19:20:57.401571Z",
                        "updated": "2022-01-24T19:20:57.401585Z"
                    },
                    "created": "2022-01-24T19:20:57.402036Z",
                    "updated": "2022-01-24T19:20:57.402049Z"
                    },
                    {
                    "id": 5,
                    "code": "3",
                    "description": "4.3. Durante el período de implementación de esta contribución, el país incorporará criterios de adaptación al cambio climático en normas y lineamientos para la inversión pública, de manera que se asegure su robustez ante impactos climáticos.",
                    "other": null,
                    "ndc_area": {
                        "id": 3,
                        "code": "4",
                        "description": "4. Infraestructura y construcción",
                        "other": null,
                        "created": "2022-01-24T19:20:57.402590Z",
                        "updated": "2022-01-24T19:20:57.402603Z"
                    },
                    "created": "2022-01-24T19:20:57.403818Z",
                    "updated": "2022-01-24T19:20:57.403830Z"
                    }
                ],
                "adaptation_axis_guideline": {
                    "id": 2,
                    "code": "2",
                    "adaptation_axis": {
                    "id": 1,
                    "code": "1",
                    "description": "Eje 1. Conocimiento, servicios climáticos y desarrollo de capacidades (Instrumental)",
                    "created": "2022-01-24T19:20:57.439091Z",
                    "updated": "2022-01-24T19:20:57.439104Z"
                    },
                    "created": "2022-01-24T19:20:57.440867Z",
                    "updated": "2022-01-24T19:20:57.440880Z"
                },
                "created": "2022-01-24T19:21:21.248414Z",
                "updated": "2022-01-24T19:21:21.248436Z"
                },
                "instrument": {
                "id": 1,
                "name": "intrument test",
                "description": "Esta es la descripcion del instrumento a utilizar",
                "created": "2022-01-24T19:21:21.254838Z",
                "updated": "2022-01-24T19:21:21.254857Z"
                },
                "climate_threat": {
                "id": 1,
                "type_climate_threat": {
                    "code": "",
                    "name": ""
                },
                "created": "2022-01-24T19:21:21.257275Z",
                "updated": "2022-01-24T19:21:21.257294Z"
                },
                "implementation": {
                " [...]

2021-10-29 22:00 UTC, Izcarmt95 requested changes

2021-10-29 22:00 UTC, Izcarmt95 commented on general/models.py
> +    #Generar predeterminado
delete this comment!

2021-10-29 22:00 UTC, Izcarmt95 commented on general/models.py
> +    #Generar predeterminado
spanish comment

2021-10-29 22:00 UTC, Izcarmt95 commented on adaptation_action/services.py
> +        print(adaptation_action_id)
delete this print

2021-10-29 22:00 UTC, Izcarmt95 commented on adaptation_action/services.py
> +        ATTRIBUTE_INSTANCE_ERROR = 'Instance Model does not have {0} attribute'
self.ATTRIBUTE_INSTANCE_ERROR

2021-10-29 22:00 UTC, Izcarmt95 commented on adaptation_action/services.py
> +        pass
delete this pass

2021-10-29 22:00 UTC, Izcarmt95 commented on adaptation_action/migrations/default_data/data_migration_0002.py
> +]
add break line

2022-01-26 02:09 UTC, Izcarmt95 requested changes
In general it is good, but this PR is too big
Please small PR

2022-01-26 02:09 UTC, Izcarmt95 commented on mitigation_action/test/test_Model.py
> +from typing import ClassVar
Why. ?

2022-01-26 02:09 UTC, Izcarmt95 commented on mitigation_action/test/test_Model.py
> +from django.db.models import fields
this is not necessary

2022-01-26 02:09 UTC, Izcarmt95 commented on adaptation_action/urls.py
> +            'api/v1/adaptation-action/get_ods/',
Please , change the ending of the endpoints, change  `_` to `-`

2022-04-07 19:14 UTC, naybort approved these changes

2022-04-07 20:13 UTC, merged